#!/usr/bin/env bash
set -euo pipefail
echo ">> Fix: use the exact required no-results sentence (لم يتم العثور على مرجع موثّق في قاعدة مكوريا.) verbatim per the spec"
mkdir -p "$(dirname "lib/i18n.ts")"
cat > "lib/i18n.ts" << 'CMFIX2_EOF'
export type Locale = "ar" | "en";

export const LOCALE_COOKIE = "makuria_locale";
export const DEFAULT_LOCALE: Locale = "ar";

export const dictionaries: Record<Locale, Record<string, string>> = {
  ar: {
    siteName: "مكوريا",
    siteTagline: "معهد مكوريا القانوني — منصة الذكاء القانوني السودانية",
    navHome: "الرئيسية",
    navLaws: "القوانين",
    navCases: "السوابق القضائية",
    navPrinciples: "المبادئ القانونية",
    navSearch: "البحث الذكي",
    navWorkspace: "مساحة المحامي",
    navLogin: "تسجيل الدخول",
    navLogout: "تسجيل الخروج",
    heroTitle: "أول منصة سودانية للذكاء القانوني",
    heroSubtitle:
      "قوانين، سوابق قضائية، ومبادئ قانونية موثّقة — بحث ذكي وتحقق من المصادر.",
    exploreLaws: "استعرض القوانين",
    exploreCases: "استعرض السوابق القضائية",
    searchPlaceholder: "ابحث في القوانين والسوابق والمواد بالكلمة المفتاحية",
    searchButton: "بحث",
    noResults: "لا توجد نتائج مطابقة",
    loadMore: "المزيد",
    previous: "السابق",
    next: "التالي",
    page: "صفحة",
    of: "من",
    verified: "موثّق",
    unverified: "غير موثّق — يتطلب مراجعة قانونية",
    comingSoonTitle: "قيد التطوير",
    comingSoonBody:
      "هذه الوحدة جزء من مساحة عمل المحامي في مكوريا وسيتم بناؤها في مرحلة لاحقة. لا توجد بيانات أو وظائف مُصطنعة هنا.",
    workspaceWelcome: "مرحبًا بك في مساحة عمل المحامي",
    workspaceEmpty: "لم يتم إنشاء أي ملفات قضايا بعد.",
    loginTitle: "تسجيل الدخول",
    signupTitle: "إنشاء حساب محامٍ",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    submit: "إرسال",
    noAccount: "ليس لديك حساب؟",
    haveAccount: "لديك حساب بالفعل؟",
    createAccount: "إنشاء حساب",
    signIn: "تسجيل الدخول",
    articlesCount: "مادة",
    lawNumber: "رقم القانون",
    yearIssued: "سنة الإصدار",
    court: "المحكمة",
    caseNumber: "رقم القضية",
    judgmentDate: "تاريخ الحكم",
    footerRights: "جميع الحقوق محفوظة",
    footerNotice:
      "المحتوى القانوني في هذه النسخة التجريبية مصدره نفس قاعدة بيانات مكوريا الإنتاجية — لا يوجد محتوى مُصطنع.",

    // Case Mapper (Phase 1)
    cmPageTitle: "خريطة القضية — Case Mapper",
    cmFactsLabel: "أدخل وقائع القضية",
    cmFactsPlaceholder: "اكتب وقائع القضية بالتفصيل بالعربية...",
    cmCaseType: "نوع القضية",
    cmCourt: "المحكمة",
    cmJurisdiction: "الولاية / الاختصاص",
    cmIncidentDate: "تاريخ الواقعة",
    cmKeywords: "كلمات مفتاحية",
    cmAnalyzeButton: "حلّل القضية",
    cmAnalyzing: "جارٍ التحليل...",
    cmEmptyFacts: "الرجاء إدخال وقائع القضية قبل التحليل.",
    cmErrorState: "حدث خطأ أثناء تحليل القضية. يرجى المحاولة مرة أخرى.",
    cmNoResultsAtAll:
      "لم يتم العثور على مرجع موثّق في قاعدة مكوريا. جرّب إضافة كلمات مفتاحية أكثر تحديدًا.",
    cmSectionSummary: "ملخص الوقائع",
    cmSummaryNote: "عرض أولي للوقائع كما أدخلتها — بدون تفسير أو استنتاج.",
    cmSummaryTruncated: "(تم عرض الجزء الأول من النص المدخل)",
    cmSectionIssues: "المسائل القانونية المحتملة",
    cmIssuesNote: "زوايا بحث أولية مستخرجة آليًا من النص المدخل — تحليل تمهيدي، وليست تكييفًا قانونيًا نهائيًا.",
    cmIssueOriginCaseType: "من نوع القضية",
    cmIssueOriginKeyword: "من الكلمات المفتاحية",
    cmIssueOriginExtracted: "مستخرجة من نص الوقائع",
    cmSectionLaws: "القوانين والمواد ذات الصلة",
    cmSectionCases: "السوابق القضائية ذات الصلة",
    cmSectionPrinciples: "المبادئ القانونية",
    cmSectionMap: "خريطة الربط",
    cmSectionSources: "المصادر",
    cmMatchedOn: "تمت المطابقة على",
    cmArticleLabel: "المادة",
    cmNoLaws: "لا توجد قوانين أو مواد مطابقة لهذه المسألة.",
    cmNoCases: "لا توجد سوابق قضائية مطابقة لهذه المسألة.",
    cmNoPrinciples: "لا توجد مبادئ قانونية مطابقة لهذه المسألة.",
    cmMapFacts: "الوقائع",
    cmMapIssue: "المسألة القانونية",
    cmMapLaw: "النص القانوني",
    cmMapCase: "السابقة القضائية",
    cmMapPrinciple: "المبدأ القانوني",
    cmAuthorityVerified: "موثّق",
    cmAuthorityNeedsReview: "يحتاج مراجعة",
    cmAuthorityOverruled: "منقوض — لا يُستشهد به كسند قائم",
    cmAuthorityUnverified: "غير متحقق",
    cmSourceLink: "مصدر الوثيقة",
    cmSourceUnavailable: "المصدر غير متاح في قاعدة مكوريا",
    cmAnalysisLabel: "تحليل — وليس سندًا قانونيًا",
    cmAuthorityLabel: "سند قانوني موثّق من قاعدة مكوريا",
    cmRelevanceReason: "سبب الصلة",
    cmDisclaimer:
      "خريطة القضية أداة بحث أولية تعرض فقط ما هو موجود فعليًا في قاعدة بيانات مكوريا. أي استنتاج أو تصنيف هنا هو تحليل آلي أولي يتطلب مراجعة محامٍ مرخّص، وليس رأيًا قانونيًا.",
  },
  en: {
    siteName: "Makuria",
    siteTagline: "Makuria Legal Institute — Sudanese Legal Intelligence Platform",
    navHome: "Home",
    navLaws: "Laws",
    navCases: "Judicial Precedents",
    navPrinciples: "Legal Principles",
    navSearch: "Smart Search",
    navWorkspace: "Lawyer Workspace",
    navLogin: "Log in",
    navLogout: "Log out",
    heroTitle: "Sudan's First AI-Powered Legal Intelligence Platform",
    heroSubtitle:
      "Verified laws, judicial precedents, and legal principles — smart search with source verification.",
    exploreLaws: "Browse Laws",
    exploreCases: "Browse Precedents",
    searchPlaceholder: "Search laws, cases, and articles by keyword",
    searchButton: "Search",
    noResults: "No matching results",
    loadMore: "Load more",
    previous: "Previous",
    next: "Next",
    page: "Page",
    of: "of",
    verified: "Verified",
    unverified: "Unverified — requires legal review",
    comingSoonTitle: "Coming Soon",
    comingSoonBody:
      "This module is part of the Makuria Lawyer Workspace and will be built in a later phase. No fabricated data or functionality lives here.",
    workspaceWelcome: "Welcome to your Lawyer Workspace",
    workspaceEmpty: "No matters have been created yet.",
    loginTitle: "Log in",
    signupTitle: "Create a lawyer account",
    email: "Email",
    password: "Password",
    submit: "Submit",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    createAccount: "Create account",
    signIn: "Log in",
    articlesCount: "articles",
    lawNumber: "Law No.",
    yearIssued: "Year issued",
    court: "Court",
    caseNumber: "Case No.",
    judgmentDate: "Judgment date",
    footerRights: "All rights reserved",
    footerNotice:
      "Legal content on this staging build is sourced from the same production Makuria database — nothing here is fabricated.",

    // Case Mapper (Phase 1)
    cmPageTitle: "Case Mapper — خريطة القضية",
    cmFactsLabel: "Enter the case facts",
    cmFactsPlaceholder: "Describe the case facts in detail...",
    cmCaseType: "Case type",
    cmCourt: "Court",
    cmJurisdiction: "Jurisdiction",
    cmIncidentDate: "Incident date",
    cmKeywords: "Keywords",
    cmAnalyzeButton: "Analyze case",
    cmAnalyzing: "Analyzing...",
    cmEmptyFacts: "Please enter the case facts before analyzing.",
    cmErrorState: "Something went wrong analyzing the case. Please try again.",
    cmNoResultsAtAll:
      "No verified authority was found in the Makuria database. Try adding more specific keywords.",
    cmSectionSummary: "Facts Summary",
    cmSummaryNote: "A plain preview of the facts as entered — no interpretation or inference.",
    cmSummaryTruncated: "(showing the leading portion of the text you entered)",
    cmSectionIssues: "Potential Legal Issues",
    cmIssuesNote: "Preliminary search angles extracted mechanically from the text — an initial pass, not a final legal classification.",
    cmIssueOriginCaseType: "from case type",
    cmIssueOriginKeyword: "from keywords",
    cmIssueOriginExtracted: "extracted from the facts",
    cmSectionLaws: "Related Laws & Articles",
    cmSectionCases: "Related Precedents",
    cmSectionPrinciples: "Legal Principles",
    cmSectionMap: "Relationship Map",
    cmSectionSources: "Sources",
    cmMatchedOn: "Matched on",
    cmArticleLabel: "Article",
    cmNoLaws: "No matching law or article found for this issue.",
    cmNoCases: "No matching precedent found for this issue.",
    cmNoPrinciples: "No matching legal principle found for this issue.",
    cmMapFacts: "Facts",
    cmMapIssue: "Legal Issue",
    cmMapLaw: "Legal Text",
    cmMapCase: "Precedent",
    cmMapPrinciple: "Legal Principle",
    cmAuthorityVerified: "Verified",
    cmAuthorityNeedsReview: "Needs review",
    cmAuthorityOverruled: "Overruled — not citable as standing authority",
    cmAuthorityUnverified: "Unverified",
    cmSourceLink: "Source document",
    cmSourceUnavailable: "Source not available in the Makuria database",
    cmAnalysisLabel: "Analysis — not legal authority",
    cmAuthorityLabel: "Verified legal authority from the Makuria database",
    cmRelevanceReason: "Relevance",
    cmDisclaimer:
      "Case Mapper is a preliminary research tool that only surfaces what actually exists in the Makuria database. Any grouping or inference here is preliminary automated analysis requiring review by a licensed lawyer, not a legal opinion.",
  },
};

export function t(locale: Locale, key: string): string {
  return dictionaries[locale][key] ?? dictionaries[DEFAULT_LOCALE][key] ?? key;
}

export function dirFor(locale: Locale): "rtl" | "ltr" {
  return locale === "ar" ? "rtl" : "ltr";
}

CMFIX2_EOF
rm -- "$0" 2>/dev/null || true
git add -A
git commit -m "Use the exact required Arabic no-results-found sentence in Case Mapper"
git push
echo ">> Done. Vercel will auto-deploy from this push."
